[package]
name = "bloco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.2.0"
thiserror = "1.0.30"
uluru = "3.0.0"
